#ifndef LOGSINFO_H
#define LOGSINFO_H

class SLog
{
public:
    QString logFilename;
    int frame;
};

namespace logsInfo
{
    static const int nFramesBefore		= 9;
    static const int nFramesAfter               = 10;
    static const int logSize 			= 114;
    static const SLog logs[logSize]= { 	{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 1054}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 5581}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 5715}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 6933}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 9849}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 16132}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 18681}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 22529}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 26416}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 27744}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict1"), 28880}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 1225},
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 1386}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 2059}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 3579}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 4402}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 5938}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict2"), 7907},
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 8913}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 12586},
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 15313}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 16770}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 17434}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 18466}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 22366}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 24501}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 26651}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict3"), 33384}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict4"), 1431}, 
					{QString("/STOxs-ZJUNlict/STOxs-ZJUNlict4"), 2767},
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 3475},
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 4285}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 5047}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 5266}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 7245}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 8062}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 10845}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 12656}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 12807}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 15886}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons1"), 17692}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 3319}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 3386}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 4713}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 5684}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 7620}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 9342}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 10760}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 14512}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 15465},//50 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 16590}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 17504}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 18655}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 21761}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 28008}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 37987}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 42372}, 
					{QString("/STOxs-CMDragons/STOxs-CMDragons2"), 45493},
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons1"), 1238}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons1"), 4617}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons1"), 32092}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons1"), 38994}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons1"), 40644}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons2"), 8796}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons3"), 1385}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons3"), 1626}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons3"), 8076}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons3"), 8164}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons3"), 15960}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons4"), 6136}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons4"), 13817}, 
					{QString("/STOxs-RoboDragons/STOxs-RoboDragons4"), 15384},
					{QString("/STOxs-MCT/STOxs-MCT1"), 7714}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 13465}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 19240}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 19372}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 24443}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 25337}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 31570}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 34214}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 34381}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 36532}, 
					{QString("/STOxs-MCT/STOxs-MCT1"), 41875}, 
					{QString("/STOxs-MCT/STOxs-MCT2"), 8412}, 
					{QString("/STOxs-MCT/STOxs-MCT2"), 15101}, 
					{QString("/STOxs-MCT/STOxs-MCT2"), 18138}, 
					{QString("/STOxs-MCT/STOxs-MCT3"), 1123}, 
					{QString("/STOxs-MCT/STOxs-MCT3"), 8378}, 
					{QString("/STOxs-MCT/STOxs-MCT3"), 11522}, 
					{QString("/STOxs-MCT/STOxs-MCT3"), 19138},
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders1"), 1221}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders1"), 2605}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders1"), 7560}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 2113},
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 4934}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 10312}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 11957}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 13569}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders2"), 16778},
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 1571},//100 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 2052}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 2171}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 2268}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 4096}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 5253}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 5600}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 9374}, 
					{QString("/STOxs-NEUIslanders/STOxs-NEUIslanders3"), 11971},
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets1"), 5169}, 
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets1"), 6181}, 
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets1"), 18254}, 
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets1"), 41841},
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets2"), 4961}, 
					{QString("/STOxs-RoboJackets/STOxs-RoboJackets2"), 11203}};
    
}

#endif